const CountriesOfImg = {
  defaultCountry: "https://i.imgur.com/zcUyjm1.png",
  afeganistão: "https://d1gx1e6ikts5pb.cloudfront.net/afg.svg",
  "ilhas de aland": "https://d1gx1e6ikts5pb.cloudfront.net/ala.svg",
  albânia: "https://d1gx1e6ikts5pb.cloudfront.net/alb.svg",
  argélia: "https://d1gx1e6ikts5pb.cloudfront.net/dza.svg",
  "samoa americana": "https://d1gx1e6ikts5pb.cloudfront.net/asm.svg",
  andorra: "https://d1gx1e6ikts5pb.cloudfront.net/and.svg",
  angola: "https://d1gx1e6ikts5pb.cloudfront.net/ago.svg",
  anguila: "https://d1gx1e6ikts5pb.cloudfront.net/aia.svg",
  antártida: "https://d1gx1e6ikts5pb.cloudfront.net/ata.svg",
  "antígua e barbuda": "https://d1gx1e6ikts5pb.cloudfront.net/atg.svg",
  argentina: "https://d1gx1e6ikts5pb.cloudfront.net/arg.svg",
  armênia: "https://d1gx1e6ikts5pb.cloudfront.net/arm.svg",
  aruba: "https://d1gx1e6ikts5pb.cloudfront.net/abw.svg",
  austrália: "https://d1gx1e6ikts5pb.cloudfront.net/aus.svg",
  áustria: "https://d1gx1e6ikts5pb.cloudfront.net/aut.svg",
  azerbaijão: "https://d1gx1e6ikts5pb.cloudfront.net/aze.svg",
  bahamas: "https://d1gx1e6ikts5pb.cloudfront.net/bhs.svg",
  bahrein: "https://d1gx1e6ikts5pb.cloudfront.net/bhr.svg",
  bangladesh: "https://d1gx1e6ikts5pb.cloudfront.net/bgd.svg",
  barbados: "https://d1gx1e6ikts5pb.cloudfront.net/brb.svg",
  bielorrússia: "https://d1gx1e6ikts5pb.cloudfront.net/blr.svg",
  bélgica: "https://d1gx1e6ikts5pb.cloudfront.net/bel.svg",
  belize: "https://d1gx1e6ikts5pb.cloudfront.net/blz.svg",
  benin: "https://d1gx1e6ikts5pb.cloudfront.net/ben.svg",
  bermudas: "https://d1gx1e6ikts5pb.cloudfront.net/bmu.svg",
  butão: "https://d1gx1e6ikts5pb.cloudfront.net/btn.svg",
  bolívia: "https://d1gx1e6ikts5pb.cloudfront.net/bol.svg",
  bonaire: "https://d1gx1e6ikts5pb.cloudfront.net/bes.svg",
  "bósnia e herzegovina": "https://d1gx1e6ikts5pb.cloudfront.net/bih.svg",
  botsuana: "https://d1gx1e6ikts5pb.cloudfront.net/bwa.svg",
  "ilha bouvet": "https://d1gx1e6ikts5pb.cloudfront.net/bvt.svg",
  brasil: "https://d1gx1e6ikts5pb.cloudfront.net/bra.svg",
  "território britânico do oceano íídico": "https://d1gx1e6ikts5pb.cloudfront.net/iot.svg",
  "ilhas menores distantes dos estados unidos": "https://d1gx1e6ikts5pb.cloudfront.net/umi.svg",
  "ilhas virgens britânicas": "https://d1gx1e6ikts5pb.cloudfront.net/vgb.svg",
  "ilhas virgens americanas": "https://d1gx1e6ikts5pb.cloudfront.net/vir.svg",
  brunei: "https://d1gx1e6ikts5pb.cloudfront.net/brn.svg",
  bulgária: "https://d1gx1e6ikts5pb.cloudfront.net/bgr.svg",
  "burkina faso": "https://d1gx1e6ikts5pb.cloudfront.net/bfa.svg",
  burundi: "https://d1gx1e6ikts5pb.cloudfront.net/bdi.svg",
  camboja: "https://d1gx1e6ikts5pb.cloudfront.net/khm.svg",
  camarões: "https://d1gx1e6ikts5pb.cloudfront.net/cmr.svg",
  canadá: "https://d1gx1e6ikts5pb.cloudfront.net/can.svg",
  "cabo verde": "https://d1gx1e6ikts5pb.cloudfront.net/cpv.svg",
  "ilhas cayman": "https://d1gx1e6ikts5pb.cloudfront.net/cym.svg",
  "república centro-africana": "https://d1gx1e6ikts5pb.cloudfront.net/caf.svg",
  chade: "https://d1gx1e6ikts5pb.cloudfront.net/tcd.svg",
  chile: "https://d1gx1e6ikts5pb.cloudfront.net/chl.svg",
  china: "https://d1gx1e6ikts5pb.cloudfront.net/chn.svg",
  "ilha christmas": "https://d1gx1e6ikts5pb.cloudfront.net/cxr.svg",
  "ilhas cocos": "https://d1gx1e6ikts5pb.cloudfront.net/cck.svg",
  colômbia: "https://d1gx1e6ikts5pb.cloudfront.net/col.svg",
  comores: "https://d1gx1e6ikts5pb.cloudfront.net/com.svg",
  congo: "https://d1gx1e6ikts5pb.cloudfront.net/cog.svg",
  "rd congo": "https://d1gx1e6ikts5pb.cloudfront.net/cod.svg",
  "ilhas cook": "https://d1gx1e6ikts5pb.cloudfront.net/cok.svg",
  "costa rica": "https://d1gx1e6ikts5pb.cloudfront.net/cri.svg",
  croácia: "https://d1gx1e6ikts5pb.cloudfront.net/hrv.svg",
  cuba: "https://d1gx1e6ikts5pb.cloudfront.net/cub.svg",
  curaçao: "https://d1gx1e6ikts5pb.cloudfront.net/cuw.svg",
  chipre: "https://d1gx1e6ikts5pb.cloudfront.net/cyp.svg",
  "república tcheca": "https://d1gx1e6ikts5pb.cloudfront.net/cze.svg",
  dinamarca: "https://d1gx1e6ikts5pb.cloudfront.net/dnk.svg",
  djibuti: "https://d1gx1e6ikts5pb.cloudfront.net/dji.svg",
  dominica: "https://d1gx1e6ikts5pb.cloudfront.net/dma.svg",
  "república dominicana": "https://d1gx1e6ikts5pb.cloudfront.net/dom.svg",
  equador: "https://d1gx1e6ikts5pb.cloudfront.net/ecu.svg",
  egito: "https://d1gx1e6ikts5pb.cloudfront.net/egy.svg",
  "el salvador": "https://d1gx1e6ikts5pb.cloudfront.net/slv.svg",
  "guiné equatorial": "https://d1gx1e6ikts5pb.cloudfront.net/gnq.svg",
  eritreia: "https://d1gx1e6ikts5pb.cloudfront.net/eri.svg",
  estônia: "https://d1gx1e6ikts5pb.cloudfront.net/est.svg",
  etiópia: "https://d1gx1e6ikts5pb.cloudfront.net/eth.svg",
  "ilhas malvinas": "https://d1gx1e6ikts5pb.cloudfront.net/flk.svg",
  "ilhas faroé": "https://d1gx1e6ikts5pb.cloudfront.net/fro.svg",
  fiji: "https://d1gx1e6ikts5pb.cloudfront.net/fji.svg",
  finlândia: "https://d1gx1e6ikts5pb.cloudfront.net/fin.svg",
  frança: "https://d1gx1e6ikts5pb.cloudfront.net/fra.svg",
  "guiana francesa": "https://d1gx1e6ikts5pb.cloudfront.net/guf.svg",
  "polinésia francesa": "https://d1gx1e6ikts5pb.cloudfront.net/pyf.svg",
  "terras austrais e antárticas francesas": "https://d1gx1e6ikts5pb.cloudfront.net/atf.svg",
  gabão: "https://d1gx1e6ikts5pb.cloudfront.net/gab.svg",
  gâmbia: "https://d1gx1e6ikts5pb.cloudfront.net/gmb.svg",
  geórgia: "https://d1gx1e6ikts5pb.cloudfront.net/geo.svg",
  alemanha: "https://d1gx1e6ikts5pb.cloudfront.net/deu.svg",
  gana: "https://d1gx1e6ikts5pb.cloudfront.net/gha.svg",
  gibraltar: "https://d1gx1e6ikts5pb.cloudfront.net/gib.svg",
  grécia: "https://d1gx1e6ikts5pb.cloudfront.net/grc.svg",
  groelândia: "https://d1gx1e6ikts5pb.cloudfront.net/grl.svg",
  granada: "https://d1gx1e6ikts5pb.cloudfront.net/grd.svg",
  guadalupe: "https://d1gx1e6ikts5pb.cloudfront.net/glp.svg",
  guam: "https://d1gx1e6ikts5pb.cloudfront.net/gum.svg",
  guatemala: "https://d1gx1e6ikts5pb.cloudfront.net/gtm.svg",
  guernsey: "https://d1gx1e6ikts5pb.cloudfront.net/ggy.svg",
  guiné: "https://d1gx1e6ikts5pb.cloudfront.net/gin.svg",
  "guiné-bissau": "https://d1gx1e6ikts5pb.cloudfront.net/gnb.svg",
  guiana: "https://d1gx1e6ikts5pb.cloudfront.net/guy.svg",
  haiti: "https://d1gx1e6ikts5pb.cloudfront.net/hti.svg",
  "ilha heard e ilhas mcdonald": "https://d1gx1e6ikts5pb.cloudfront.net/hmd.svg",
  vaticano: "https://d1gx1e6ikts5pb.cloudfront.net/vat.svg",
  honduras: "https://d1gx1e6ikts5pb.cloudfront.net/hnd.svg",
  "hong kong": "https://d1gx1e6ikts5pb.cloudfront.net/hkg.svg",
  hungria: "https://d1gx1e6ikts5pb.cloudfront.net/hun.svg",
  islândia: "https://d1gx1e6ikts5pb.cloudfront.net/isl.svg",
  índia: "https://d1gx1e6ikts5pb.cloudfront.net/ind.svg",
  indonésia: "https://d1gx1e6ikts5pb.cloudfront.net/idn.svg",
  "costa do marfim": "https://d1gx1e6ikts5pb.cloudfront.net/civ.svg",
  irã: "https://d1gx1e6ikts5pb.cloudfront.net/irn.svg",
  iraque: "https://d1gx1e6ikts5pb.cloudfront.net/irq.svg",
  irlanda: "https://d1gx1e6ikts5pb.cloudfront.net/irl.svg",
  "ilha de man": "https://d1gx1e6ikts5pb.cloudfront.net/imn.svg",
  israel: "https://d1gx1e6ikts5pb.cloudfront.net/isr.svg",
  itália: "https://d1gx1e6ikts5pb.cloudfront.net/ita.svg",
  jamaica: "https://d1gx1e6ikts5pb.cloudfront.net/jam.svg",
  japão: "https://d1gx1e6ikts5pb.cloudfront.net/jpn.svg",
  jersey: "https://d1gx1e6ikts5pb.cloudfront.net/jey.svg",
  jordânia: "https://d1gx1e6ikts5pb.cloudfront.net/jor.svg",
  cazaquistão: "https://d1gx1e6ikts5pb.cloudfront.net/kaz.svg",
  quênia: "https://d1gx1e6ikts5pb.cloudfront.net/ken.svg",
  kiribati: "https://d1gx1e6ikts5pb.cloudfront.net/kir.svg",
  kuwait: "https://d1gx1e6ikts5pb.cloudfront.net/kwt.svg",
  quirguistão: "https://d1gx1e6ikts5pb.cloudfront.net/kgz.svg",
  laos: "https://d1gx1e6ikts5pb.cloudfront.net/lao.svg",
  letônia: "https://d1gx1e6ikts5pb.cloudfront.net/lva.svg",
  líbano: "https://d1gx1e6ikts5pb.cloudfront.net/lbn.svg",
  lesoto: "https://d1gx1e6ikts5pb.cloudfront.net/lso.svg",
  libéria: "https://d1gx1e6ikts5pb.cloudfront.net/lbr.svg",
  líbia: "https://d1gx1e6ikts5pb.cloudfront.net/lby.svg",
  liechtenstein: "https://d1gx1e6ikts5pb.cloudfront.net/lie.svg",
  lituânia: "https://d1gx1e6ikts5pb.cloudfront.net/ltu.svg",
  luxemburgo: "https://d1gx1e6ikts5pb.cloudfront.net/lux.svg",
  macau: "https://d1gx1e6ikts5pb.cloudfront.net/mac.svg",
  macedônia: "https://d1gx1e6ikts5pb.cloudfront.net/mkd.svg",
  madagascar: "https://d1gx1e6ikts5pb.cloudfront.net/mdg.svg",
  malawi: "https://d1gx1e6ikts5pb.cloudfront.net/mwi.svg",
  malásia: "https://d1gx1e6ikts5pb.cloudfront.net/mys.svg",
  maldivas: "https://d1gx1e6ikts5pb.cloudfront.net/mdv.svg",
  mali: "https://d1gx1e6ikts5pb.cloudfront.net/mli.svg",
  malta: "https://d1gx1e6ikts5pb.cloudfront.net/mlt.svg",
  "ilhas marshall": "https://d1gx1e6ikts5pb.cloudfront.net/mhl.svg",
  martinica: "https://d1gx1e6ikts5pb.cloudfront.net/mtq.svg",
  mauritânia: "https://d1gx1e6ikts5pb.cloudfront.net/mrt.svg",
  maurício: "https://d1gx1e6ikts5pb.cloudfront.net/mus.svg",
  mayotte: "https://d1gx1e6ikts5pb.cloudfront.net/myt.svg",
  méxico: "https://d1gx1e6ikts5pb.cloudfront.net/mex.svg",
  micronésia: "https://d1gx1e6ikts5pb.cloudfront.net/fsm.svg",
  moldávia: "https://d1gx1e6ikts5pb.cloudfront.net/mda.svg",
  mônaco: "https://d1gx1e6ikts5pb.cloudfront.net/mco.svg",
  mongólia: "https://d1gx1e6ikts5pb.cloudfront.net/mng.svg",
  montenegro: "https://d1gx1e6ikts5pb.cloudfront.net/mne.svg",
  montserrat: "https://d1gx1e6ikts5pb.cloudfront.net/msr.svg",
  marrocos: "https://d1gx1e6ikts5pb.cloudfront.net/mar.svg",
  moçambique: "https://d1gx1e6ikts5pb.cloudfront.net/moz.svg",
  myanmar: "https://d1gx1e6ikts5pb.cloudfront.net/mmr.svg",
  namíbia: "https://d1gx1e6ikts5pb.cloudfront.net/nam.svg",
  nauru: "https://d1gx1e6ikts5pb.cloudfront.net/nru.svg",
  nepal: "https://d1gx1e6ikts5pb.cloudfront.net/npl.svg",
  holanda: "https://d1gx1e6ikts5pb.cloudfront.net/nld.svg",
  "nova caledônia": "https://d1gx1e6ikts5pb.cloudfront.net/ncl.svg",
  "nova zelândia": "https://d1gx1e6ikts5pb.cloudfront.net/nzl.svg",
  nicarágua: "https://d1gx1e6ikts5pb.cloudfront.net/nic.svg",
  níger: "https://d1gx1e6ikts5pb.cloudfront.net/ner.svg",
  nigéria: "https://d1gx1e6ikts5pb.cloudfront.net/nga.svg",
  niue: "https://d1gx1e6ikts5pb.cloudfront.net/niu.svg",
  "ilha norfolk": "https://d1gx1e6ikts5pb.cloudfront.net/nfk.svg",
  "coreia do norte": "https://d1gx1e6ikts5pb.cloudfront.net/prk.svg",
  "ilhas marianas": "https://d1gx1e6ikts5pb.cloudfront.net/mnp.svg",
  noruega: "https://d1gx1e6ikts5pb.cloudfront.net/nor.svg",
  omã: "https://d1gx1e6ikts5pb.cloudfront.net/omn.svg",
  paquistão: "https://d1gx1e6ikts5pb.cloudfront.net/pak.svg",
  palau: "https://d1gx1e6ikts5pb.cloudfront.net/plw.svg",
  palestina: "https://d1gx1e6ikts5pb.cloudfront.net/pse.svg",
  panamá: "https://d1gx1e6ikts5pb.cloudfront.net/pan.svg",
  "papua nova guiné": "https://d1gx1e6ikts5pb.cloudfront.net/png.svg",
  paraguai: "https://d1gx1e6ikts5pb.cloudfront.net/pry.svg",
  peru: "https://d1gx1e6ikts5pb.cloudfront.net/per.svg",
  filipinas: "https://d1gx1e6ikts5pb.cloudfront.net/phl.svg",
  "ilhas pitcairn": "https://d1gx1e6ikts5pb.cloudfront.net/pcn.svg",
  polônia: "https://d1gx1e6ikts5pb.cloudfront.net/pol.svg",
  portugal: "https://d1gx1e6ikts5pb.cloudfront.net/prt.svg",
  "porto rico": "https://d1gx1e6ikts5pb.cloudfront.net/pri.svg",
  catar: "https://d1gx1e6ikts5pb.cloudfront.net/qat.svg",
  kosovo: "https://d1gx1e6ikts5pb.cloudfront.net/kos.svg",
  reunião: "https://d1gx1e6ikts5pb.cloudfront.net/reu.svg",
  romênia: "https://d1gx1e6ikts5pb.cloudfront.net/rou.svg",
  rússia: "https://d1gx1e6ikts5pb.cloudfront.net/rus.svg",
  russia: "https://d1gx1e6ikts5pb.cloudfront.net/rus.svg",
  ruanda: "https://d1gx1e6ikts5pb.cloudfront.net/rwa.svg",
  "são bartolomeu": "https://d1gx1e6ikts5pb.cloudfront.net/blm.svg",
  "santa helena": "https://d1gx1e6ikts5pb.cloudfront.net/shn.svg",
  "são cristóvão e neves": "https://d1gx1e6ikts5pb.cloudfront.net/kna.svg",
  "santa lúcia": "https://d1gx1e6ikts5pb.cloudfront.net/lca.svg",
  "saint martin": "https://d1gx1e6ikts5pb.cloudfront.net/maf.svg",
  "saint-pierre e miquelon": "https://d1gx1e6ikts5pb.cloudfront.net/spm.svg",
  "são vicente e granadinas": "https://d1gx1e6ikts5pb.cloudfront.net/vct.svg",
  samoa: "https://d1gx1e6ikts5pb.cloudfront.net/wsm.svg",
  "san marino": "https://d1gx1e6ikts5pb.cloudfront.net/smr.svg",
  "são tomé e príncipe": "https://d1gx1e6ikts5pb.cloudfront.net/stp.svg",
  "arábia saudita": "https://d1gx1e6ikts5pb.cloudfront.net/sau.svg",
  senegal: "https://d1gx1e6ikts5pb.cloudfront.net/sen.svg",
  sérvia: "https://d1gx1e6ikts5pb.cloudfront.net/srb.svg",
  seicheles: "https://d1gx1e6ikts5pb.cloudfront.net/syc.svg",
  "serra leoa": "https://d1gx1e6ikts5pb.cloudfront.net/sle.svg",
  singapura: "https://d1gx1e6ikts5pb.cloudfront.net/sgp.svg",
  "sint maarten": "https://d1gx1e6ikts5pb.cloudfront.net/sxm.svg",
  eslováquia: "https://d1gx1e6ikts5pb.cloudfront.net/svk.svg",
  eslovênia: "https://d1gx1e6ikts5pb.cloudfront.net/svn.svg",
  "ilhas salomão": "https://d1gx1e6ikts5pb.cloudfront.net/slb.svg",
  somália: "https://d1gx1e6ikts5pb.cloudfront.net/som.svg",
  "república sul-africana": "https://d1gx1e6ikts5pb.cloudfront.net/zaf.svg",
  "ilhas geórgias do sul e sandwich do sul": "https://d1gx1e6ikts5pb.cloudfront.net/sgs.svg",
  "república da coreia": "https://d1gx1e6ikts5pb.cloudfront.net/kor.svg",
  "coreia do sul": "https://d1gx1e6ikts5pb.cloudfront.net/kor.svg",
  "sudão do sul": "https://d1gx1e6ikts5pb.cloudfront.net/ssd.svg",
  espanha: "https://d1gx1e6ikts5pb.cloudfront.net/esp.svg",
  "sri lanka": "https://d1gx1e6ikts5pb.cloudfront.net/lka.svg",
  sudão: "https://d1gx1e6ikts5pb.cloudfront.net/sdn.svg",
  suriname: "https://d1gx1e6ikts5pb.cloudfront.net/sur.svg",
  svalbard: "https://d1gx1e6ikts5pb.cloudfront.net/sjm.svg",
  suazilândia: "https://d1gx1e6ikts5pb.cloudfront.net/swz.svg",
  suécia: "https://d1gx1e6ikts5pb.cloudfront.net/swe.svg",
  suíça: "https://d1gx1e6ikts5pb.cloudfront.net/che.svg",
  síria: "https://d1gx1e6ikts5pb.cloudfront.net/syr.svg",
  taiwan: "https://d1gx1e6ikts5pb.cloudfront.net/twn.svg",
  tajiquistão: "https://d1gx1e6ikts5pb.cloudfront.net/tjk.svg",
  tanzânia: "https://d1gx1e6ikts5pb.cloudfront.net/tza.svg",
  tailândia: "https://d1gx1e6ikts5pb.cloudfront.net/tha.svg",
  "timor leste": "https://d1gx1e6ikts5pb.cloudfront.net/tls.svg",
  togo: "https://d1gx1e6ikts5pb.cloudfront.net/tgo.svg",
  tokelau: "https://d1gx1e6ikts5pb.cloudfront.net/tkl.svg",
  tonga: "https://d1gx1e6ikts5pb.cloudfront.net/ton.svg",
  "trinidad e tobago": "https://d1gx1e6ikts5pb.cloudfront.net/tto.svg",
  tunísia: "https://d1gx1e6ikts5pb.cloudfront.net/tun.svg",
  turquia: "https://d1gx1e6ikts5pb.cloudfront.net/tur.svg",
  turcomenistão: "https://d1gx1e6ikts5pb.cloudfront.net/tkm.svg",
  "ilhas turcas e caicos": "https://d1gx1e6ikts5pb.cloudfront.net/tca.svg",
  tuvalu: "https://d1gx1e6ikts5pb.cloudfront.net/tuv.svg",
  uganda: "https://d1gx1e6ikts5pb.cloudfront.net/uga.svg",
  ucrânia: "https://d1gx1e6ikts5pb.cloudfront.net/ukr.svg",
  "emirados árabes unidos": "https://d1gx1e6ikts5pb.cloudfront.net/are.svg",
  "reino unido": "https://d1gx1e6ikts5pb.cloudfront.net/gbr.svg",
  "estados unidos": "https://d1gx1e6ikts5pb.cloudfront.net/usa.svg",
  uruguai: "https://d1gx1e6ikts5pb.cloudfront.net/ury.svg",
  uzbequistão: "https://d1gx1e6ikts5pb.cloudfront.net/uzb.svg",
  vanuatu: "https://d1gx1e6ikts5pb.cloudfront.net/vut.svg",
  venezuela: "https://d1gx1e6ikts5pb.cloudfront.net/ven.svg",
  vietnã: "https://d1gx1e6ikts5pb.cloudfront.net/vnm.svg",
  "wallis e futuna": "https://d1gx1e6ikts5pb.cloudfront.net/wlf.svg",
  "saara ocidental": "https://d1gx1e6ikts5pb.cloudfront.net/esh.svg",
  iêmen: "https://d1gx1e6ikts5pb.cloudfront.net/yem.svg",
  zâmbia: "https://d1gx1e6ikts5pb.cloudfront.net/zmb.svg",
  zimbabwe: "https://d1gx1e6ikts5pb.cloudfront.net/zwe.svg",
  afghanistan: "https://d1gx1e6ikts5pb.cloudfront.net/afg.svg",
  "åland islands": "https://d1gx1e6ikts5pb.cloudfront.net/ala.svg",
  albania: "https://d1gx1e6ikts5pb.cloudfront.net/alb.svg",
  algeria: "https://d1gx1e6ikts5pb.cloudfront.net/dza.svg",
  "american samoa": "https://d1gx1e6ikts5pb.cloudfront.net/asm.svg",
  anguilla: "https://d1gx1e6ikts5pb.cloudfront.net/aia.svg",
  antarctica: "https://d1gx1e6ikts5pb.cloudfront.net/ata.svg",
  "antigua and barbuda": "https://d1gx1e6ikts5pb.cloudfront.net/atg.svg",
  arménia: "https://d1gx1e6ikts5pb.cloudfront.net/arm.svg",
  armenia: "https://d1gx1e6ikts5pb.cloudfront.net/arm.svg",
  australia: "https://d1gx1e6ikts5pb.cloudfront.net/aus.svg",
  austria: "https://d1gx1e6ikts5pb.cloudfront.net/aut.svg",
  azerbaijan: "https://d1gx1e6ikts5pb.cloudfront.net/aze.svg",
  bahrain: "https://d1gx1e6ikts5pb.cloudfront.net/bhr.svg",
  belarus: "https://d1gx1e6ikts5pb.cloudfront.net/blr.svg",
  belgium: "https://d1gx1e6ikts5pb.cloudfront.net/bel.svg",
  bermuda: "https://d1gx1e6ikts5pb.cloudfront.net/bmu.svg",
  bhutan: "https://d1gx1e6ikts5pb.cloudfront.net/btn.svg",
  "bolivia (plurinational state of)": "https://d1gx1e6ikts5pb.cloudfront.net/bol.svg",
  "bonaire, sint eustatius and saba": "https://d1gx1e6ikts5pb.cloudfront.net/bes.svg",
  "bosnia and herzegovina": "https://d1gx1e6ikts5pb.cloudfront.net/bih.svg",
  botswana: "https://d1gx1e6ikts5pb.cloudfront.net/bwa.svg",
  "bouvet island": "https://d1gx1e6ikts5pb.cloudfront.net/bvt.svg",
  brazil: "https://d1gx1e6ikts5pb.cloudfront.net/bra.svg",
  "british indian ocean territory": "https://d1gx1e6ikts5pb.cloudfront.net/iot.svg",
  "united states minor outlying islands": "https://d1gx1e6ikts5pb.cloudfront.net/umi.svg",
  "virgin islands (british)": "https://d1gx1e6ikts5pb.cloudfront.net/vgb.svg",
  "virgin islands (u.s.)": "https://d1gx1e6ikts5pb.cloudfront.net/vir.svg",
  "brunei darussalam": "https://d1gx1e6ikts5pb.cloudfront.net/brn.svg",
  bulgaria: "https://d1gx1e6ikts5pb.cloudfront.net/bgr.svg",
  cambodia: "https://d1gx1e6ikts5pb.cloudfront.net/khm.svg",
  cameroon: "https://d1gx1e6ikts5pb.cloudfront.net/cmr.svg",
  canada: "https://d1gx1e6ikts5pb.cloudfront.net/can.svg",
  "cayman islands": "https://d1gx1e6ikts5pb.cloudfront.net/cym.svg",
  "central african republic": "https://d1gx1e6ikts5pb.cloudfront.net/caf.svg",
  chad: "https://d1gx1e6ikts5pb.cloudfront.net/tcd.svg",
  "christmas island": "https://d1gx1e6ikts5pb.cloudfront.net/cxr.svg",
  "cocos (keeling) islands": "https://d1gx1e6ikts5pb.cloudfront.net/cck.svg",
  colombia: "https://d1gx1e6ikts5pb.cloudfront.net/col.svg",
  comoros: "https://d1gx1e6ikts5pb.cloudfront.net/com.svg",
  "congo (democratic republic of the)": "https://d1gx1e6ikts5pb.cloudfront.net/cod.svg",
  "cook islands": "https://d1gx1e6ikts5pb.cloudfront.net/cok.svg",
  croatia: "https://d1gx1e6ikts5pb.cloudfront.net/hrv.svg",
  cyprus: "https://d1gx1e6ikts5pb.cloudfront.net/cyp.svg",
  "czech republic": "https://d1gx1e6ikts5pb.cloudfront.net/cze.svg",
  denmark: "https://d1gx1e6ikts5pb.cloudfront.net/dnk.svg",
  djibouti: "https://d1gx1e6ikts5pb.cloudfront.net/dji.svg",
  "dominican republic": "https://d1gx1e6ikts5pb.cloudfront.net/dom.svg",
  ecuador: "https://d1gx1e6ikts5pb.cloudfront.net/ecu.svg",
  egypt: "https://d1gx1e6ikts5pb.cloudfront.net/egy.svg",
  "equatorial guinea": "https://d1gx1e6ikts5pb.cloudfront.net/gnq.svg",
  eritrea: "https://d1gx1e6ikts5pb.cloudfront.net/eri.svg",
  estonia: "https://d1gx1e6ikts5pb.cloudfront.net/est.svg",
  ethiopia: "https://d1gx1e6ikts5pb.cloudfront.net/eth.svg",
  "falkland islands (malvinas)": "https://d1gx1e6ikts5pb.cloudfront.net/flk.svg",
  "faroe islands": "https://d1gx1e6ikts5pb.cloudfront.net/fro.svg",
  finland: "https://d1gx1e6ikts5pb.cloudfront.net/fin.svg",
  france: "https://d1gx1e6ikts5pb.cloudfront.net/fra.svg",
  "french guiana": "https://d1gx1e6ikts5pb.cloudfront.net/guf.svg",
  "french polynesia": "https://d1gx1e6ikts5pb.cloudfront.net/pyf.svg",
  "french southern territories": "https://d1gx1e6ikts5pb.cloudfront.net/atf.svg",
  gabon: "https://d1gx1e6ikts5pb.cloudfront.net/gab.svg",
  gambia: "https://d1gx1e6ikts5pb.cloudfront.net/gmb.svg",
  georgia: "https://d1gx1e6ikts5pb.cloudfront.net/geo.svg",
  germany: "https://d1gx1e6ikts5pb.cloudfront.net/deu.svg",
  ghana: "https://d1gx1e6ikts5pb.cloudfront.net/gha.svg",
  greece: "https://d1gx1e6ikts5pb.cloudfront.net/grc.svg",
  greenland: "https://d1gx1e6ikts5pb.cloudfront.net/grl.svg",
  grenada: "https://d1gx1e6ikts5pb.cloudfront.net/grd.svg",
  guadeloupe: "https://d1gx1e6ikts5pb.cloudfront.net/glp.svg",
  guinea: "https://d1gx1e6ikts5pb.cloudfront.net/gin.svg",
  "guinea-bissau": "https://d1gx1e6ikts5pb.cloudfront.net/gnb.svg",
  guyana: "https://d1gx1e6ikts5pb.cloudfront.net/guy.svg",
  "heard island and mcdonald islands": "https://d1gx1e6ikts5pb.cloudfront.net/hmd.svg",
  "holy see": "https://d1gx1e6ikts5pb.cloudfront.net/vat.svg",
  hungary: "https://d1gx1e6ikts5pb.cloudfront.net/hun.svg",
  iceland: "https://d1gx1e6ikts5pb.cloudfront.net/isl.svg",
  india: "https://d1gx1e6ikts5pb.cloudfront.net/ind.svg",
  indonesia: "https://d1gx1e6ikts5pb.cloudfront.net/idn.svg",
  "côte divoire": "https: // restcountries.com/data/civ.svg",
  "iran (islamic republic of)": "https://d1gx1e6ikts5pb.cloudfront.net/irn.svg",
  iraq: "https://d1gx1e6ikts5pb.cloudfront.net/irq.svg",
  ireland: "https://d1gx1e6ikts5pb.cloudfront.net/irl.svg",
  "isle of man": "https://d1gx1e6ikts5pb.cloudfront.net/imn.svg",
  italy: "https://d1gx1e6ikts5pb.cloudfront.net/ita.svg",
  japan: "https://d1gx1e6ikts5pb.cloudfront.net/jpn.svg",
  jordan: "https://d1gx1e6ikts5pb.cloudfront.net/jor.svg",
  kazakhstan: "https://d1gx1e6ikts5pb.cloudfront.net/kaz.svg",
  kenya: "https://d1gx1e6ikts5pb.cloudfront.net/ken.svg",
  kyrgyzstan: "https://d1gx1e6ikts5pb.cloudfront.net/kgz.svg",
  "lao peoples democratic republic": "https: // restcountries.com/data/lao.svg",
  latvia: "https://d1gx1e6ikts5pb.cloudfront.net/lva.svg",
  lebanon: "https://d1gx1e6ikts5pb.cloudfront.net/lbn.svg",
  lesotho: "https://d1gx1e6ikts5pb.cloudfront.net/lso.svg",
  liberia: "https://d1gx1e6ikts5pb.cloudfront.net/lbr.svg",
  libya: "https://d1gx1e6ikts5pb.cloudfront.net/lby.svg",
  lithuania: "https://d1gx1e6ikts5pb.cloudfront.net/ltu.svg",
  luxembourg: "https://d1gx1e6ikts5pb.cloudfront.net/lux.svg",
  macao: "https://d1gx1e6ikts5pb.cloudfront.net/mac.svg",
  "macedonia (the former yugoslav republic of)": "https://d1gx1e6ikts5pb.cloudfront.net/mkd.svg",
  malaysia: "https://d1gx1e6ikts5pb.cloudfront.net/mys.svg",
  maldives: "https://d1gx1e6ikts5pb.cloudfront.net/mdv.svg",
  "marshall islands": "https://d1gx1e6ikts5pb.cloudfront.net/mhl.svg",
  martinique: "https://d1gx1e6ikts5pb.cloudfront.net/mtq.svg",
  mauritania: "https://d1gx1e6ikts5pb.cloudfront.net/mrt.svg",
  mauritius: "https://d1gx1e6ikts5pb.cloudfront.net/mus.svg",
  mexico: "https://d1gx1e6ikts5pb.cloudfront.net/mex.svg",
  "micronesia (federated states of)": "https://d1gx1e6ikts5pb.cloudfront.net/fsm.svg",
  "moldova (republic of)": "https://d1gx1e6ikts5pb.cloudfront.net/mda.svg",
  monaco: "https://d1gx1e6ikts5pb.cloudfront.net/mco.svg",
  mongolia: "https://d1gx1e6ikts5pb.cloudfront.net/mng.svg",
  morocco: "https://d1gx1e6ikts5pb.cloudfront.net/mar.svg",
  mozambique: "https://d1gx1e6ikts5pb.cloudfront.net/moz.svg",
  "países baixos": "https://d1gx1e6ikts5pb.cloudfront.net/nld.svg",
  netherlands: "https://d1gx1e6ikts5pb.cloudfront.net/nld.svg",
  "new caledonia": "https://d1gx1e6ikts5pb.cloudfront.net/ncl.svg",
  "new zealand": "https://d1gx1e6ikts5pb.cloudfront.net/nzl.svg",
  nicaragua: "https://d1gx1e6ikts5pb.cloudfront.net/nic.svg",
  niger: "https://d1gx1e6ikts5pb.cloudfront.net/ner.svg",
  nigeria: "https://d1gx1e6ikts5pb.cloudfront.net/nga.svg",
  "norfolk island": "https://d1gx1e6ikts5pb.cloudfront.net/nfk.svg",
  "korea (democratic peoples republic of)": "https: // restcountries.com/data/prk.svg",
  "northern mariana islands": "https://d1gx1e6ikts5pb.cloudfront.net/mnp.svg",
  norway: "https://d1gx1e6ikts5pb.cloudfront.net/nor.svg",
  oman: "https://d1gx1e6ikts5pb.cloudfront.net/omn.svg",
  pakistan: "https://d1gx1e6ikts5pb.cloudfront.net/pak.svg",
  "palestine, state of": "https://d1gx1e6ikts5pb.cloudfront.net/pse.svg",
  panama: "https://d1gx1e6ikts5pb.cloudfront.net/pan.svg",
  "papua new guinea": "https://d1gx1e6ikts5pb.cloudfront.net/png.svg",
  paraguay: "https://d1gx1e6ikts5pb.cloudfront.net/pry.svg",
  philippines: "https://d1gx1e6ikts5pb.cloudfront.net/phl.svg",
  pitcairn: "https://d1gx1e6ikts5pb.cloudfront.net/pcn.svg",
  poland: "https://d1gx1e6ikts5pb.cloudfront.net/pol.svg",
  "puerto rico": "https://d1gx1e6ikts5pb.cloudfront.net/pri.svg",
  qatar: "https://d1gx1e6ikts5pb.cloudfront.net/qat.svg",
  "republic of kosovo": "https://d1gx1e6ikts5pb.cloudfront.net/kos.svg",
  réunion: "https://d1gx1e6ikts5pb.cloudfront.net/reu.svg",
  roménia: "https://d1gx1e6ikts5pb.cloudfront.net/rou.svg",
  romania: "https://d1gx1e6ikts5pb.cloudfront.net/rou.svg",
  "russian federation": "https://d1gx1e6ikts5pb.cloudfront.net/rus.svg",
  rwanda: "https://d1gx1e6ikts5pb.cloudfront.net/rwa.svg",
  "saint barthélemy": "https://d1gx1e6ikts5pb.cloudfront.net/blm.svg",
  "saint helena, ascension and tristan da cunha": "https://d1gx1e6ikts5pb.cloudfront.net/shn.svg",
  "saint kitts and nevis": "https://d1gx1e6ikts5pb.cloudfront.net/kna.svg",
  "saint lucia": "https://d1gx1e6ikts5pb.cloudfront.net/lca.svg",
  "saint martin (french part)": "https://d1gx1e6ikts5pb.cloudfront.net/maf.svg",
  "saint pierre and miquelon": "https://d1gx1e6ikts5pb.cloudfront.net/spm.svg",
  "saint vincent and the grenadines": "https://d1gx1e6ikts5pb.cloudfront.net/vct.svg",
  "sao tome and principe": "https://d1gx1e6ikts5pb.cloudfront.net/stp.svg",
  "saudi arabia": "https://d1gx1e6ikts5pb.cloudfront.net/sau.svg",
  serbia: "https://d1gx1e6ikts5pb.cloudfront.net/srb.svg",
  seychelles: "https://d1gx1e6ikts5pb.cloudfront.net/syc.svg",
  "sierra leone": "https://d1gx1e6ikts5pb.cloudfront.net/sle.svg",
  singapore: "https://d1gx1e6ikts5pb.cloudfront.net/sgp.svg",
  "sint maarten (dutch part)": "https://d1gx1e6ikts5pb.cloudfront.net/sxm.svg",
  slovakia: "https://d1gx1e6ikts5pb.cloudfront.net/svk.svg",
  eslovénia: "https://d1gx1e6ikts5pb.cloudfront.net/svn.svg",
  slovenia: "https://d1gx1e6ikts5pb.cloudfront.net/svn.svg",
  "solomon islands": "https://d1gx1e6ikts5pb.cloudfront.net/slb.svg",
  somalia: "https://d1gx1e6ikts5pb.cloudfront.net/som.svg",
  "áfrica do sul": "https://d1gx1e6ikts5pb.cloudfront.net/zaf.svg",
  "south africa": "https://d1gx1e6ikts5pb.cloudfront.net/zaf.svg",
  "south georgia and the south sandwich islands": "https://d1gx1e6ikts5pb.cloudfront.net/sgs.svg",
  "korea (republic of)": "https://d1gx1e6ikts5pb.cloudfront.net/kor.svg",
  "south sudan": "https://d1gx1e6ikts5pb.cloudfront.net/ssd.svg",
  spain: "https://d1gx1e6ikts5pb.cloudfront.net/esp.svg",
  sudan: "https://d1gx1e6ikts5pb.cloudfront.net/sdn.svg",
  "svalbard and jan mayen": "https://d1gx1e6ikts5pb.cloudfront.net/sjm.svg",
  swaziland: "https://d1gx1e6ikts5pb.cloudfront.net/swz.svg",
  sweden: "https://d1gx1e6ikts5pb.cloudfront.net/swe.svg",
  switzerland: "https://d1gx1e6ikts5pb.cloudfront.net/che.svg",
  "syrian arab republic": "https://d1gx1e6ikts5pb.cloudfront.net/syr.svg",
  tajikistan: "https://d1gx1e6ikts5pb.cloudfront.net/tjk.svg",
  "tanzania, united republic of": "https://d1gx1e6ikts5pb.cloudfront.net/tza.svg",
  thailand: "https://d1gx1e6ikts5pb.cloudfront.net/tha.svg",
  "timor-leste": "https://d1gx1e6ikts5pb.cloudfront.net/tls.svg",

  "trinidad and tobago": "https://d1gx1e6ikts5pb.cloudfront.net/tto.svg",
  tunisia: "https://d1gx1e6ikts5pb.cloudfront.net/tun.svg",
  turkey: "https://d1gx1e6ikts5pb.cloudfront.net/tur.svg",
  turkmenistan: "https://d1gx1e6ikts5pb.cloudfront.net/tkm.svg",
  "turks and caicos islands": "https://d1gx1e6ikts5pb.cloudfront.net/tca.svg",
  ukraine: "https://d1gx1e6ikts5pb.cloudfront.net/ukr.svg",
  "united arab emirates": "https://d1gx1e6ikts5pb.cloudfront.net/are.svg",
  "united kingdom of great britain and northern ireland":
    "https://d1gx1e6ikts5pb.cloudfront.net/gbr.svg",
  "united states of america": "https://d1gx1e6ikts5pb.cloudfront.net/usa.svg",
  uruguay: "https://d1gx1e6ikts5pb.cloudfront.net/ury.svg",
  uzbekistan: "https://d1gx1e6ikts5pb.cloudfront.net/uzb.svg",
  "venezuela (bolivarian republic of)": "https://d1gx1e6ikts5pb.cloudfront.net/ven.svg",
  "viet nam": "https://d1gx1e6ikts5pb.cloudfront.net/vnm.svg",
  "wallis and futuna": "https://d1gx1e6ikts5pb.cloudfront.net/wlf.svg",
  "western sahara": "https://d1gx1e6ikts5pb.cloudfront.net/esh.svg",
  yemen: "https://d1gx1e6ikts5pb.cloudfront.net/yem.svg",
  zambia: "https://d1gx1e6ikts5pb.cloudfront.net/zmb.svg",
  "país de gales": "https://upload.wikimedia.org/wikipedia/commons/d/dc/Flag_of_Wales.svg",
  "irlanda do norte":
    "https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Northern_Ireland_%281953%E2%80%931972%29.svg",
  inglaterra: "https://upload.wikimedia.org/wikipedia/commons/b/be/Flag_of_England.svg",
  england: "https://upload.wikimedia.org/wikipedia/commons/b/be/Flag_of_England.svg",
  escócia: "https://upload.wikimedia.org/wikipedia/commons/1/10/Flag_of_Scotland.svg",
};

type CountrysTypes = keyof typeof CountriesOfImg;

export default function getImageCountry(country: string) {
  const normalizedCountry = `${country.toLowerCase()}` as CountrysTypes;
  return CountriesOfImg[normalizedCountry] || CountriesOfImg.defaultCountry;
}
