export const messagesErrors: { [key: number]: string } = {
  1: "Erro ao enviar código, tente novamente.",
  2: "Código inválido, insira-o corretamente.",
  20: "Falha ao enviar sua solicitação para nossa base. Contacte o suporte.",
  500: "Desculpe, sua solicitação está demorando mais do que o esperado. Por favor, tente novamente.",
  1000: "Nome de usuário inválido.",
  1001: "Username inválido.",
  1002: "Tipo de usuário inválido.",
  1003: "Contato de usuário inválido.",
  1004: "Cidade do usuário inválida.",
  1005: "Usuário já existe.",
  1006: "Remover créditos do usuário.",
  1007: "Editar créditos do usuário supervisor.",
  1008: "Editar créditos do usuário da sede.",
  1009: "Erro desconhecido.",
  1010: "CPF já cadastrado.",
  1011: "País do usuário inválido.",
  1012: "Email inválido.",
  1013: "Documento do usuário inválido.",
  1014: "Documento já existe.",
  1016: "E-mail não conferem.",
  1020: "Parâmetro ID inválido.",
  1021: "Usuário não autorizado.",
  1022: "Usuário não encontrado.",
  1023: "Usuário não confirmado.",
  1024: "Meta do usuário igual aos créditos.",
  1025: "Erro ao bloquear/desbloquear o sistema.",
  1026: "Telefone do usuário inválido.",
  1027: "Data de nascimento do usuário inválida.",
  1028: "Gênero do usuário inválido.",
  1029: "Senha inválida.",
  1030: "Erro desconhecido no login.",
  1031: "Usuário/Senha incorreto.",
  1032: "Aposta esportiva inválida.",
  1033: "Crédito insuficiente para apostar.",
  1034: "Cartão não encontrado.",
  1036: "Crédito insuficiente no cartão para apostar.",
  1037: "Cartão sem usuário.",
  1038: "Valor mínimo da aposta é de R$1,00.",
  1039: "Tamanho de aposta esportiva inválido.",
  1040: "Placar correto inválido.",
  1041: "Senha incorreta.",
  1042: "Probabilidade do jogador inválida.",
  1043: "Cotação de futebol inválida.",
  1044: "Cotação de tempo de futebol inválida.",
  1045: "Cotação de MMA inválida.",
  1046: "Cotação inválida.",
  1047: "Limite individual do usuário excedido.",
  1048: "Limite duplo do usuário excedido.",
  1049: "Limite total do usuário excedido.",
  1050: "Limite individual do esporte excedido.",
  1051: "Limite duplo do esporte excedido.",
  1052: "Limite total do esporte excedido.",
  1053: "Aposta não pode ser cancelada.",
  1054: "Aposta não pode ser rejeitada.",
  1055: "Não pode cancelar a aposta de outro usuário.",
  1056: "Não pode finalizar a aposta de outro usuário.",
  1057: "Valor máximo da aposta excedido.",
  1058: "Aposta repetida.",
  1059: "Nome do apostador necessário.",
  1060: "PIN do cartão inválido.",
  1061: "Crédito insuficiente para criar cartão.",
  1062: "Valor mínimo do cartão excedido.",
  1063: "Valor máximo do cartão excedido.",
  1064: "Bônus insuficiente.",
  1065: "Créditos e bônus insuficientes no cartão.",
  1068: "Limite para criar cartão excedido.",
  1069: "Limite para criar cartão excedido pelo valor.",
  1070: "Erro no banco de dados.",
  1071: "Cotação de corrida inválida.",
  1072: "Aposta esportiva repetida.",
  1073: "Cartão não excluído, contém aposta.",
  1074: "Cotação de desafio inválida.",
  1075: "Moeda do usuário inválida.",
  1076: "CPF inválido.",
  1077: "Promoção já ativa entre as datas.",
  1078: "Não foi possível encontrar a promoção.",
  1079: "Valor de depósito inválido para promoção.",
  1080: "Créditos insuficientes.",
  1081: "Não foi possível carregar os dados do usuário.",
  1082: "Usuário bloqueado.",
  1083: "Sede bloqueada.",
  1084: "Usuário bloqueado pela central.",
  1085: "Nenhuma zona de gerente associada a esta sede.",
  1086: "Ajuda variável desativada para este usuário.",
  1087: "Localização ausente.",
  1088: "Fichas insuficientes.",
  1089: "Usuário não autorizado a ver a aposta.",
  1090: "Pré-aposta não encontrada.",
  1091: "Valor de cotação inválido.",
  1092: "Valor de cotação inválido ao carregar pré-aposta.",
  1093: "Jogo ao vivo, pré-jogo bloqueado.",
  1094: "Cotação de tempo inválida.",
  1095: "Margem inválida.",
  1096: "Pontuação inválida.",
  1097: "Aposta repetida por hash.",
  1098: "Probabilidade do próximo placar inválida.",
  1099: "Aposta não pode conter esportes e desafios.",
  1100: "Sistema bloqueado.",
  1101: "Valores inválidos.",
  1102: "Sistema em manutenção.",
  1103: "Não foi possível carregar os dados.",
  1104: "Sistema de apostas bloqueado.",
  1105: "O sistema deve estar bloqueado para apostas.",
  1106: "O sistema deve ter um resumo atualizado salvo.",
  1107: "Configuração de contas desnecessária.",
  1108: "Um ou mais pagamentos a serem validados.",
  1109: "Intervalo inválido entre lançamentos.",
  1110: "Liberação em andamento.",
  1111: "Usuário já usou a promoção.",
  1112: "Usuário já usou uma promoção nos últimos 60 dias.",
  1113: "Não pode usar scratch off.",
  1114: "Bônus de associado inválido.",
  1115: "Limite individual de apostas ao vivo excedido.",
  1116: "Limite duplo de apostas ao vivo excedido.",
  1117: "Limite diário individual excedido.",
  1118: "Limite de cotações individuais excedido.",
  1119: "Limite diário de apostas ao vivo excedido.",
  1120: "Transação repetida.",
  1121: "Pagamento no fim de semana.",
  1122: "Não é possível salvar resumos iguais no mesmo dia.",
  1123: "Não é possível alterar o sistema de bloqueio enquanto a liberação está em andamento.",
  1124: "Limite de cotações ao vivo individuais excedido.",
  1125: "Limite de cotações esportivas excedido.",
  1126: "Limite mensal de depósito por boleto excedido.",
  1127: "Limite semanal de depósito por boleto excedido.",
  1128: "Limite diário de depósito por boleto excedido.",
  1129: "Intervalo de tempo entre transações não permitido.",
  1130: "Limite duplo de cotações esportivas excedido.",
  1131: "Meta do usuário não definida.",
  1132: "Mudança forçada de senha.",
  1133: "Código de autenticação de dois fatores gerado.",
  1134: "Verifique o e-mail para o código de autenticação de dois fatores.",
  1135: "Insira o código 2FA.",
  1136: "Autenticação de dois fatores requer e-mail válido.",
  1137: "Você excedeu o limite de depósitos diários. Tente novamente amanhã.",
  1138: "Limite de depósito próprio excedido em 7 dias.",
  1139: "Limite de depósito próprio excedido em 30 dias.",
  1140: "Conta possui saldo.",
  1141: "Conta possui apostas abertas.",
  1142: "Conta em período de pausa ativo.",
  1143: "Conta possui saldo e apostas abertas.",
  1144: "Odds inválidos.",
  1145: "Código Enet já está em uso.",
  1146: "Informação PIX inválida.",
  1147: "Usuário já realizou uma retirada hoje.",
  1148: "Código de autenticação expirado.",
  1150: "Lote já registrado.",
  1151: "Cupom já expirado.",
  1152: "Cupom já utilizado.",
  1153: "Código de cupom inválido.",
  1154: "Intervalo inválido entre o uso de cu opons.",
  1155: "Cupom não encontrado.",
  1156: "ID do cupom inválido.",
  1157: "Cupom já associado.",
  1158: "Não é possível associar o cupom a este usuário.",
  1159: "Não é possível associar o usuário de outra sede.",
  1160: "Não é possível associar o usuário de outra supervisão.",
  1161: "Não é possível associar o cupom sem usuário.",
  1162: "Não foi possível encontrar o código promocional.",
  1163: "Código promocional já existe.",
  1164: "Código promocional já expirado.",
  1165: "Código promocional ja utilizado.",
  1166: "Código promocional inválido.",
  1167: "Valor mínimo de depósito inválido para o código promocional.",
  1170: "Usuário bloqueado para apostas de um jogo.",
  1171: "Usuário bloqueado para apostas de dois jogos.",
  1172: "Valor de validação do cartão enviado.",
  1173: "Cliente bloqueado para uso do cartão.",
  1174: "Valor de validação do cartão ausente.",
  1175: "Valor de validação do cartão incorreto.",
  1176: "Cliente só pode validar um cartão a cada 15 dias.",
  1177: "Valor de validação do cartão expirado, um novo foi enviado.",
  1178: "Número máximo de cartões diferentes por dia atingido.",
  1179: "Cartão já registrado no sistema.",
  1180: "Dados do cartão inválidos.",
  1181: "Cliente bloqueado durante o dia todo.",
  1182: "Solicitação de retirada PIX já enviada.",
  1183: "Não é possível continuar, notificação em algo diferente de ambos.",
  1184: "Usuário atingiu o máximo de retiradas recusadas.",
  1185: "Acesso à plataforma revogado para o usuário.",
  1186: "Valor máximo de aposta excedido para combinação de PC.",
  1187: "Usuário excedeu o número de apostas para combinação de PC.",
  1188: "Não há jogos suficientes para a promoção.",
  1189: "Usuário não se registrou no intervalo da promoção.",
  1190: "Aposta promocional deve ter 1 ou 2 esportes.",
  1191: "Sede excedeu o limite para combinação de jogos.",
  1192: "Não foi possível encontrar o gerente.",
  1193: "Não foi possível encontrar o supervisor.",
  1194: "Cliente possui tipo de afiliação padrão.",
  1195: "Usuário excedeu o limite para combinação de jogos.",
  1196: "Não é possível fazer o cashout da aposta.",
  1197: "Não é possível fazer o cashout da aposta porque o valor mudou além do limite.",
  1198: "Código de autenticação de dois fatores ausente.",
  1199: "Não é possível continuar sem habilitar a autenticação de dois fatores.",
  1200: "Limite de três ou mais esportes excedido.",
  1201: "Limite mensal de retirada excedido.",
  1202: "Estamos realizando uma manutenção programada em nosso site para melhorar sua experiência. No momento, estão ocorrendo erros de saque. Pedimos desculpas pelo inconveniente. Voltaremos em breve para oferecer um serviço ainda melhor. Agradecemos sua compreensão!",
  1203: "Não é possível remover o esporte.",
  1204: "Meta X inválida.",
  1205: "Limite total de usuário de esporte excedido.",
  1206: "Data de registro do usuário inválida.",
  1207: "Bônus de registro indisponível.",
  1208: "Tipo de depósito inválido.",
  1209: "Conta Skrill inválida.",
  1210: "Não há necessidade de liberar créditos.",
  1250: "Necessita de mais dois jogos.",
  1251: "Probabilidade maior que um meio.",
  1252: "Selecione a carteira.",
  1253: "Não pode repetir o jogo no bônus.",
  1400: "Crédito insuficiente no cartão eletrônico.",
  1401: "Limite excedido pelo cartão eletrônico.",
  1402: "Limite excedido pelo valor do cartão eletrônico.",
  1300: "Código de usuário inválido.",
  1301: "Bloqueio de responsabilidade.",
  1302: "Valor máximo de aposta para bônus.",
  1500: "Senhas não conferem.",
  1501: "CPF é obrigatório.",
  1502: "A Senha deve ter pelo menos 6 caracteres",
  2001: "Quantidade de dezenas inválida.",
  2002: "Dezenas repetidas.",
  3001: "Configurações de vaquejada indefinidas.",
  4001: "Jogo não terminado.",
  5000: "Aposta não pode conter mais de 1 desafio.",
  5001: "Probabilidade permitida em pênaltis.",
  5002: "Probabilidade permitida na prorrogação.",
  5003: "Contém desafio com conflito.",
  5004: "Limite de um jogo excedido.",
  5005: "Limite de um jogo excedido pelo valor da aposta.",
  5006: "Limite de dois jogos excedido.",
  5007: "Limite de dois jogos excedido pelo valor da aposta.",
  5008: "Limite de três ou mais jogos excedido.",
  5009: "Limite de três ou mais jogos excedido pelo valor da aposta.",
  5010: "Limite de aposta em um jogo por usuário excedido.",
  5011: "Limite de aposta excedido para Lucky Six.",
  5012: "Esporte em análise para aposta individual.",
  5013: "Esporte em análise para aposta dupla.",
  5014: "Valor máximo de aposta com 1 esporte limitado.",
  5015: "Valor máximo de aposta com 2 esportes limitado.",
  5016: "Valor máximo de aposta com 3 ou mais esportes limitado.",
  5017: "Número de sets inválido.",
  5018: "Número de escanteios inválido.",
  5019: "Aposta não pode conter esportes e e-sports.",
  5020: "Limite de aposta excedido para e-sports.",
  5021: "Não pode apostar em um e-sport que vai demorar muito para acontecer.",
  5022: "Não pode apostar em um acumulado que vai demorar muito para acontecer.",
  5999: "Token de visualização de aposta inválido.",
  6000: "Aposta não encontrada.",
  6001: "Valor máximo de depósito inválido.",
  6002: "Valor mínimo para depósito é de R$ 1,00.",
  6003: "Créditos insuficientes para depósito.",
  6004: "Identidade não confirmada.",
  6005: "Endereço incompleto.",
  6006: "Dados bancários incompletos.",
  6007: "Créditos de depósito indisponíveis.",
  6008: "Parâmetros de saque inválidos.",
  6009: "Conta P4F inválida.",
  6010: "Tipo de saque inválido.",
  6011: "Valor de depósito inválido.",
  6012: "Não foi possível encontrar um depósito válido.",
  6013: "Depósito repetido.",
  6014: "Erro de validação Recaptcha.",
  6015: "Depósito já pago.",
  6016: "Valor máximo de saque inválido.",
  7000: "Dados obrigatórios do cliente.",
  7001: "Telefone já em uso.",
  7002: "Email já cadastrado.",
  7003: "Apelido já cadastrado.",
  7004: "Parâmetros faltando.",
  7005: "Conta de cliente já confirmada.",
  7006: "Código de verificação inválido.",
  7007: "Código de verificação expirado.",
  7008: "Cliente não encontrado.",
  7010: "Comprimento de senha inválido.",
  7011: "Cliente não possui o tipo de verificação fornecido.",
  7012: "Cliente não possui nenhum tipo de verificação.",
  7013: "Intervalo inválido entre geração de códigos. Espere um pouco e tente novamente.",
  7009: "Não é possível prosseguir porque o usuário não tem depósito pago que possa gerar bônus.",
  7014: "Não é possível prosseguir porque o usuário tem vários depósitos pagos.",
  8000: "Nome da sala já existe.",
  8001: "Mesa de poker já foi revertida.",
  8002: "Mesa de poker já foi encerrada.",
  8003: "Parâmetros de cassino inválidos.",
  8004: "Tipo de mesa de poker incorreto.",
  8005: "Não foi possível carregar a mesa de poker.",
  8006: "O valor do prêmio da mesa de poker não pode ser maior que o valor gasto.",
  8007: "Parâmetro de cassino inválido.",
  8008: "Erro interno do cassino.",
  8009: "Usuário não autorizado no cassino.",
  8010: "Usuário da API não autorizado no cassino.",
  8011: "Créditos insuficientes no cassino.",
  8012: "Operação de cassino inválida.",
  8013: "Direção de transferência inválida.",
  8014: "Token expirado, usuário não autorizado.",
  8015: "Usuário não encontrado no cassino.",
  8016: "Cassino em manutenção.",
  8017: "Código de hash inválido.",
  8018: "Segundo erro interno do cassino.",
  8200: "Não foi possível carregar o acumulado.",
  8201: "Pontuação do jogo ausente.",
  8202: "Pontuação do jogo inválida.",
  8203: "Limite de aposta excedido para o acumulado.",
  8204: "Acumulado indisponível.",
  8250: "Dados bancários inválidos.",
  8251: "CPF/CNPJ inválido.",
  8252: "Código do banco de destino inválido.",
  8300: "Tipo de transferência inválido.",
  8301: "Créditos insuficientes para transferir.",
  8302: "Mesa de poker ativa durante a transferência.",
  8303: "Depósito não é uma transferência bancária.",
  8304: "Não é possível alterar o status porque o depósito não está pendente.",
  8305: "Depósito já confirmado.",
  8400: "Limite excedido para geração de créditos.",
  8401: "Código de crédito inválido.",
  8402: "Crédito já utilizado.",
  8403: "Crédito já expirado.",
  8405: "Valor mínimo de crédito excedido.",
  8406: "Valor máximo de crédito excedido.",
  8407: "Crédito já cancelado.",
  8408: "Não é possível cancelar crédito de outro usuário.",
  8409: "Identificador de crédito inválido.",
  8410: "Prazo para cancelamento excedido.",
  8411: "Operação não disponível em sua região.",
  8412: "Crédito repetido.",
  8425: "Não é possível gerar boleto com CEP inválido.",
  8426: "Não é possível realizar múltiplas notificações ao mesmo tempo.",
  8427: "Tipo de notificação de cliente inválido.",
  8428: "Mensagem de notificação de cliente inválida.",
  8429: "Assunto de notificação de cliente inválido.",
  8430: "Mensagem SMS de notificação de cliente inválida.",
  8431: "Não é possível realizar mais de uma notificação por dia.",
  8432: "Não foi possível iniciar o processo de notificação.",
  8433: "Processo de notificação não identificado como parado.",
  8434: "Não foi possível continuar o processo de notificação.",
  8435: "Código de notificação de cliente inválido.",
  8436: "Link de imagem de notificação de cliente inválido.",
  8437: "Link de notificação de cliente inválido.",
  8438: "Subtítulo de notificação de cliente inválido.",
  8439: "Texto 2 de notificação de cliente inválido.",
  8440: "Texto 1 de notificação de cliente inválido.",
  8463: "Não é possível editar notificação que já foi enviada para alguém.",
  8441: "Fonte de saída inválida.",
  8442: "Não foi possível encontrar a saída.",
  8446: "Não foi possível salvar a saída.",
  8443: "Não foi possível encontrar a prestação de contas.",
  8444: "Não foi possível salvar a prestação de contas.",
  8445: "Não foi possível gerar a prestação de contas da próxima semana.",
  8447: "O sistema deve ter uma prestação de contas atualizada salva.",
  8448: "Não é possível gerar mais de uma prestação de contas por dia.",
  84490: "Não é possível criar prestação de contas com data anterior à mais antiga.",
  84489: "Não é possível criar prestação de contas com data anterior à mais antiga criada.",
  84488: "O intervalo máximo permitido é de 15 dias.",
  8449: "Não é possível editar a saída de uma prestação de contas anterior.",
  8450: "Não é possível remover a saída de uma prestação de contas anterior.",
  8451: "Não foi possível encontrar uma promoção válida.",
  8452: "Limite de um jogo acima de 1.6 na sede excedido.",
  8453: "Limite diário de apostas do cliente excedido.",
  8454: "Limite de apostas de um jogo do cliente excedido.",
  8455: "Limite de apostas de dois jogos do cliente excedido.",
  8456: "Usuário já pagou um depósito.",
  8457: "Não é possível associar cliente porque foi criado antes do usuário associado.",
  8458: "Não é possível associar cliente porque já está associado.",
  8459: "Destino de saída inválido.",
  8460: "Não é possível registrar cliente usando raspadinha e moeda diferente de BRL.",
  8461: "Não é possível registrar cliente para associar usando moeda diferente de BRL.",
  8462: "Método de depósito boleto indisponível.",
  8464: "Não é possível desfazer bônus em um depósito sem bônus.",
  8465: "Não é possível desfazer bônus em um depósito usado.",
  8466: "Não é possível desfazer bônus em um depósito não pago.",
  8467: "Não é possível desfazer bônus porque há apostas mais recentes.",
  8468: "Não é possível desfazer bônus porque o usuário não tem créditos.",
  8477: "Limite eletrônico da sede excedido.",
  8478: "Não é possível equilibrar apenas uma resposta.",
  8479: "Não é possível equilibrar mais de duas respostas.",
  8480: "Cotação inválida para resposta equilibrada.",
  8481: "Intervalo de data de consulta inválido.",
  8482: "Aposta promocional deve ter 1 esporte.",
  8483: "Aposta promocional deve ser colocada em odd PC.",
  8484: "Não há apostas promocionais disponíveis.",
  8485: "Esporte não corresponde ao esporte da promoção.",
  8486: "Usuário não fez aposta no intervalo da promoção.",
  8487: "Usuário já usou apostas gratuitas.",
  8488: "Não é possível cancelar a aposta.",
  8489: "Não é possível encerrar a aposta.",
  8490: "Usuário não fez um depósito no intervalo da promoção.",
  8491: "Depósitos do usuário não atendem aos critérios da promoção.",
  8469: "Escolhas de jogos inválidas.",
  8470: "Quantidade de escolhas de jogos inválida.",
  8471: "Escolha de jogo inválida.",
  8472: "Tipo de jogo inválido.",
  8473: "Valor de cabeça de jogo inválido.",
  8474: "Valor de jogo inválido.",
  8475: "Não foi possível encontrar Jogo do Bicho.",
  8476: "Não é possível apostar em um Jogo do Bicho antigo.",
  9001: "Captcha inválido, tente novamente.",
  9002: "Captcha inválido, tente novamente.",
  9003: "Quantidade de jogos inválida.",
  9004: "CPF não encontrado.",
  9005: "Associado não encontrado.",
  9006: "CPF já existe.",
  9007: "Depósito não encontrado.",
  9008: "Depósito já cancelado.",
  9009: "Aposta não encontrada.",
  9010: "Proibição de Recaptcha de aposta remota.",
  9011: "Proibição de Recaptcha para aposta na sede.",
  9012: "Erro de verificação do Recaptcha para usuário.",
  9013: "CPF do cliente não informado.",
  9014: "Créditos do cliente insuficientes.",
  9015: "Cliente não encontrado.",
  9016: "Associação de cliente inválida.",
  9017: "Dados de afiliação não encontrados.",
  9018: "Não é possível editar a porcentagem.",
  9019: "Cliente não foi convidado.",
  9020: "Cliente já é afiliado.",
  9021: "Cliente já é parceiro.",
  9022: "Status inválido.",
  9023: "Não é possível continuar, cliente não possui afiliação.",
  9024: "Não é possível continuar, parceiro com o mesmo nome já registrado.",
  9025: "Não é possível retirar, data do depósito de bônus inválida.",
  9026: "Loteria Marjo ausente.",
  9027: "Nome de faturamento inválido.",
  9028: "CVV do cartão inválido.",
  9029: "Número do cartão inválido.",
  9030: "Data de validade do cartão inválida.",
  9031: "Nome no cartão inválido.",
  9032: "Depósito pendente com cartão de crédito feito nos últimos 15 dias.",
  9033: "Depósito com cartão de crédito feito nos últimos 15 dias.",
  9034: "Limite de depósito com cartão de crédito excedido.",
  9035: "Nível de experiência deve ser selecionado no tutorial.",
  9036: "O valor da aposta no tutorial deve ser 10.",
  9037: "Erro no passo 1 do tutorial amador.",
  9038: "Erro no passo 2 do tutorial amador.",
  9039: "Erro no passo 3 do tutorial amador.",
  9040: "Erro no passo 4 do tutorial amador.",
  9041: "Erro no passo 5 do tutorial amador.",
  9042: "Erro no passo 1 do tutorial avançado.",
  9043: "Erro no passo 2 do tutorial avançado.",
  9044: "Erro no passo 3 do tutorial avançado.",
  9045: "Erro no passo 4 do tutorial avançado.",
  9046: "Erro no passo 5 do tutorial avançado.",
  9047: "Nível do tutorial inválido.",
  9048: "Mensagem já foi concluída.",
  9049: "Nenhum dado foi excluído.",
  9050: "Nenhum dado para atualizar.",
  9051: "Não é possível realizar várias transações de ganhadores consecutivas.",
  9052: "Não é possível desfazer várias transações de ganhadores consecutivas.",
  9053: "Não é possível continuar, a aposta já foi encerrada.",
  9054: "Fonte de transferência inválida.",
  9055: "Destino de transferência inválido.",
  9056: "Não é possível continuar, nenhuma operação adequada encontrada.",
  9057: "Retirada indisponível.",
  9058: "Já existe uma solicitação de saque pendente, aguarde alguns minutos antes de tentar novamente.",
  9059: "Limite de depósitos em 24 horas excedido.",
  9060: "Bandeira do cartão inválida.",
  9061: "Não há jogos suficientes para o jackpot.",
  9062: "Quantidade de eventos não atende aos critérios da promoção.",
  9063: "Eventos inválidos para apostar no jackpot.",
  9064: "Quantidade inválida de eventos principais selecionados.",
  9065: "Prioridade do evento inválida.",
  9066: "Categoria de prioridade do evento inválida.",
  9067: "Posição de prioridade do evento substituto inválida.",
};
